title: ESPHome Zendure SolarFlow BLE Controller
description: Unofficial local BLE controller for Zendure SolarFlow using ESPHome, Home Assistant and ESP32-S3.
theme: jekyll-theme-cayman
show_downloads: false
